main: 'xyz.mrsherobrine.ShogiCraft.ShogiCraft'
name: 'ShogiCraft'
description: "Allows you to play traditional Japanese shogi in Minecraft!"
version: '1.0'
author: 'Mrs_Herobrine_'
api-version: '1.17'
commands:
  shogi:
    description: 'Main command that handles everything'
    permission: 'shogicraft.shogi'
    usage: |
      /shogi create
      /shogi remove
      /shogi search
      /shogi challenge <player>
      /shogi challenge <accept|deny>
      /shogi surrender
      /shogi rematch <player>
      /shogi rematch <accept|deny>
permissions:
  shogicraft.shogi:
    description: 'Main permission'
    default: true